export const enum  PRODUCTS_ACTIONS_TYPES {
    FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START',
    FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED',
}

